### PR TITLE
Opencilk port, meson build, bug fix, misc maintenance

### PR DESCRIPTION
**Pull request by ailiop**
This PR contains a mix of fixes and updates.  They are summarized below.  Once these are reviewed and amended accordingly, I suggest we update the release tag to v1.0.2 (the build scripts are already updated to mark version 1.0.2 internally).

[OpenCilk]
- Replace Intel Cilk Plus array slice notation (aka vector extensions) with corresponding loops; fuse when possible.
- Remove utilities for dynamically setting # of Cilk workers.
- Update build config to allow both OpenCilk and Intel Cilk Plus.

[Build]
- Add full-fledged Meson build scripts.
- Update `configure`/`make` scripts and fix some incorrect flags.

[Dependencies]
- Fix library dependencies (remove OpenMP; add LZ4, used by FLANN).
- Allow selection of single-/multi-threaded FFTW library.

[Performance]
- Use single-threaded FFTW by default.  Multi-threaded FFTW scales poorly (even becomes slower) with more cores for non-huge grid sizes.

[README]
- Add meson build instructions.
- Update references.
- Misc edits.

[Bug fix]
- Correct mismatched `new`-`free` and `malloc`-`delete` calls.

### CODE REVIEW

**Review by pitsianis — APPROVED** [review]

**Comment by fcdimitr** [comment]
@ailiop Should we remove the previous build pipeline (autoconf, etc.) and keep only meson? I think it would be confusing if both are online. Does opencilk work with both or only with meson?

**Comment by pitsianis** [comment]
I get a FAIL, please see if you can make sense of this...

```
⋊> ~/p/s/b/opencilk ./script_meson_build_all.sh                         12:31:38
env CXX=clang++ meson --wipe -Dcilktool=none  -Dfftw_parallel_lib=none -Doptimization=2 -Denable_demos=false -Denable_matlab=true -Dmatlabroot=/Applications/MATLAB_R2020b.app -Denable_documentation=false -Ddefault_library=both -Dtune_native=true -Ddebug=true -Dprefix=/Users/nikos/projects/sgtsnepi.git/branches/opencilk/install/opencilk-none-O2 build/opencilk-none-O2
The Meson build system
Version: 0.57.1
Source dir: /Users/nikos/projects/sgtsnepi.git/branches/opencilk
Build dir: /Users/nikos/projects/sgtsnepi.git/branches/opencilk/build/opencilk-none-O2
Build type: native build
WARNING: Unknown options: "cilktool"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: sgtsnepi
Project version: 1.0.2
C++ compiler for the host machine: clang++ (clang 10.0.1 "clang version 10.0.1 (git@github.com:OpenCilk/opencilk-project.git 8435006eea5d32f9cf895a666496b89613e2cbc1)")
C++ linker for the host machine: clang++ ld64 609.8
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -fopencilk: YES 
Has header "cilk/cilk.h" : YES 
Has header "cilk/cilk_api.h" : YES 
Found pkg-config: /usr/local/bin/pkg-config (0.28)
Run-time dependency fftw3 found: YES 3.3.9
Found CMake: /usr/local/bin/cmake (3.19.1)
Run-time dependency metis found: NO (tried pkgconfig, framework and cmake)
Has header "metis.h" : YES 
Library metis found: YES
Run-time dependency tbbmalloc found: NO (tried pkgconfig, framework and cmake)
Has header "tbb/scalable_allocator.h" : YES 
Library tbbmalloc found: YES
Run-time dependency flann found: YES 1.9.1
Run-time dependency lz4 found: NO (tried pkgconfig, framework and cmake)
Has header "lz4.h" : YES 
Library lz4 found: YES
Build targets in project: 7

Option debug is: true [default: false]
Option prefix is: /Users/nikos/projects/sgtsnepi.git/branches/opencilk/install/opencilk-none-O2 [default: /Users/nikos/projects/sgtsnepi.git/branches/opencilk]
Found ninja-1.10.2 at /usr/local/bin/ninja
...
1/1 SG-t-SNE-Pi test modules FAIL            1.51s   killed by signal 11 SIGSEGV
09:29:09 MALLOC_PERTURB_=228 /Users/nikos/projects/sgtsnepi.git/branches/opencilk/build/opencilk-none-O2/test_modules
----------------------------------- output -----------------------------------


 *** TESTING SG-TSNE-PI INSTALLATION ***

 %% Using 4 threads


 - Attractive term [PQ]
   > N = 1000 D = 1...PASS
   > N = 1000 D = 2...PASS
   > N = 1000 D = 3...PASS
   > N = 2000 D = 1...PASS
   > N = 2000 D = 2...PASS
   > N = 2000 D = 3...PASS
   > N = 3000 D = 1...PASS
   > N = 3000 D = 2...PASS
   > N = 3000 D = 3...PASS

 - Repulsive term [QQ]
   > N = 1000 D = 1...PASS
   > N = 1000 D = 2...PASS
   > N = 1000 D = 3...PASS
   > N = 2000 D = 1...PASS
   > N = 2000 D = 2...PASS
   > N = 2000 D = 3...
------------------------------------------------------------------------------


Summary of Failures:

1/1 SG-t-SNE-Pi test modules FAIL            1.51s   killed by signal 11 SIGSEGV


Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

**Comment by ailiop** [comment]
> @ailiop Should we remove the previous build pipeline (autoconf, etc.) and keep only meson? I think it would be confusing if both are online. 

@fcdimitr We can remove the autoconf scripts (`configure`, `Makefile.in`).  I do think that it is simpler (and easier to maintain) to only have 1 build method.

A possible downside is if someone is unable to use Meson for some reason.  (I actually ran into that issue on a cluster environment, although I was able to patch it eventually.)  The autoconf scripts can be useful as a more portable/familiar fallback.  But then if we do want to keep around we should make it clear in the README.

I can go either way, but I'm leaning towards removing the autoconf scripts.  I'll leave it to you and @pitsianis to "push the button".  :)

> Does opencilk work with both or only with meson?

OpenCilk works with both the Meson and the autoconf scripts --- at least on my end.

**Comment by ailiop** [comment]
> 
> 
> I get a FAIL, please see if you can make sense of this...

@pitsianis Thank you for testing this!  I am not sure what the cause is.  I see that the test runs with `MALLOC_PERTURB_=228` on your end, which is not the case on mine.  Apparently, that is used to change the default initialization of data with `malloc()`, which could mean that the code is (incorrectly) relying on allocated memory being initialized to 0, somewhere.

I tried running the tests with `MALLOC_PERTURB_=228` on my end.  It did not crash, but I think my glibc version is not new enough to support it.  I also tested with `valgrind --tool=memcheck [...]` and did not get any errors/warnings about uninitialized memory.

Would you mind getting a backtrace with `gdb` and posting it here?  E.g.:
```
> gdb --args /Users/nikos/projects/sgtsnepi.git/branches/opencilk/build/opencilk-none-O2/test_modules
[...copyright info, etc...]
(gdb) run
[...program starts running, eventually crashes...]
(gdb) backtrace
[...trace info...]  <==  *copy that*
(gdb) quit
```

You may want to set the `MALLOC_PERTURB_` flag as above and/or use serial execution; e.g.:
```
> MALLOC_PERTURB_=228 CILK_NWORKERS=1 gdb --args /Users/nikos/projects/sgtsnepi.git/branches/opencilk/build/opencilk-none-O2/test_modules
```

If that is not easy or we find that we need a lot of back-and-forth, we could also arrange a live (well, Zoom) session.

**Comment by pitsianis** [comment]
Running the same thing again and again I get different FAILs

```
MALLOC_PERTURB_=18
MALLOC_PERTURB_=162
MALLOC_PERTURB_=140
```
Let's have a "live" session together...

**Comment by fcdimitr** [comment]
> > @ailiop Should we remove the previous build pipeline (autoconf, etc.) and keep only meson? I think it would be confusing if both are online.
> 
> @fcdimitr We can remove the autoconf scripts (`configure`, `Makefile.in`). I do think that it is simpler (and easier to maintain) to only have 1 build method.
> 
> A possible downside is if someone is unable to use Meson for some reason. (I actually ran into that issue on a cluster environment, although I was able to patch it eventually.) The autoconf scripts can be useful as a more portable/familiar fallback. But then if we do want to keep around we should make it clear in the README.
> 
> I can go either way, but I'm leaning towards removing the autoconf scripts. I'll leave it to you and @pitsianis to "push the button". :)
> 
> > Does opencilk work with both or only with meson?
> 
> OpenCilk works with both the Meson and the autoconf scripts --- at least on my end.

@ailiop Both Nikos and I agree that we should remove the previous build pipeline (if necessary we put it in a separate branch, in case someone has issues). So we remove it in this request, prior to merging.

**Review by fcdimitr — APPROVED** [review]
Looks good to me; we need to resolve Nikos's issue prior to merging. I will also run more experiments in the meantime.

**Review by fcdimitr — APPROVED** [review]

**Comment by ailiop** [comment]
We are having trouble replicating the error that @pitsianis is seeing, which suggests it could perhaps be specific to his system setup.  The error appears to arise with Cilk reducers and to be unrelated to the `MALLOC_PERTURB_` setting after all.

I propose that we merge the PR and create a separate issue to keep track of the problem while we try to dig deeper.

**Pull request merged**
